### ISSUE TITLE
Error when generating reports

### ISSUE THREAD

**Issue by parekhpravesh** [poldracklab/mriqc#351] opened 2017-01-31 10:36 UTC
Hello,

When running mriqc with the "--report-dir" and "--verbose-reports" parameters such as:
`mriqc <path_to_BIDS_Dataset> <path_to_Output> participant --report-dir <path_to_reports_directory> --verbose-reports -<path_to_Work>
`
the execution runs fine. The group anatomical report is generated (this dataset only has anatomical scans) and the .csv file is written. Subsequently, the following error is thrown up:

> 170131-04:46:32,58 mriqc INFO:
> 	 Summary CSV table for the anatomical data generated (/home/JPJ/Parekh/mriqc_dst_test/mriqc_dst_25Jan2017_BIDS_Test_Output/anatMRIQC.csv)
> 170131-04:46:32,283 mriqc INFO:
> 	 Group-anatomical report generated (/home/JPJ/Parekh/mriqc_dst_test/mriqc_dst_25Jan2017_BIDS_Test_Output/reports/anat_group.html)
> Traceback (most recent call last):
>   File "/home/JPJ/Enthought/Canopy_64bit/User/bin/mriqc", line 9, in <module>
>     load_entry_point('mriqc==0.9.0rc1', 'console_scripts', 'mriqc')()
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mriqc-0.9.0rc1-py2.7.egg/mriqc/bin/mriqc_run.py", line 252, in main
>     dataframe, out_csv = generate_csv(derivatives_dir, settings['output_dir'], qctype)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mriqc-0.9.0rc1-py2.7.egg/mriqc/utils/misc.py", line 173, in generate_csv
>     dataframe = dataframe.sort_values(by=all_id_fields)
>   File "/home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/frame.py", line 3229, in sort_values
>     by = by[0]
> IndexError: list index out of range

Also, the reports directory is empty. There are no files in the Output/logs folder. Please also find attached the entire output generated during the run.

P.S: This is the workstation installation of mriqc (not the server one from which the other bug #340 has been reported)

Thanks and Regards
Pravesh
[mriqc_test_run_output.txt](https://github.com/poldracklab/mriqc/files/741677/mriqc_test_run_output.txt)

**Comment by oesteban** [comment] 2017-01-31 16:40
This looks like a duplicate of #348. I'll close that one since the description here is much better.

Thanks @parekhpravesh

**Comment by oesteban** [comment] 2017-02-02 01:44
Seemingly, #352 also solved this issue. Feel free to reopen in case it re-appears

**Comment by parekhpravesh** [comment] 2017-02-02 11:47
On using the ` --verbose-reports ` flag, the pipeline writes the .csv file and saves the group HTML report. After that the following error is generated:

> Traceback (most recent call last):

>   File "/home/MBIAL/Enthought/Canopy_64bit/User/bin/mriqc", line 11, in <module>
>     load_entry_point('mriqc==0.9.0rc1', 'console_scripts', 'mriqc')()
>   File "/home/MBIAL/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mriqc/bin/mriqc_run.py", line 255, in main
>     dataframe, out_csv = generate_csv(derivatives_dir, settings['output_dir'], qctype)
>   File "/home/MBIAL/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mriqc/utils/misc.py", line 173, in generate_csv
>     dataframe = dataframe.sort_values(by=all_id_fields)
>   File "/home/MBIAL/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/frame.py", line 3229, in sort_values
>     by = by[0]
> IndexError: list index out of range

**Comment by parekhpravesh** [comment] 2017-02-03 06:15
@oesteban I am unable to re-open the issue (apparently issues closed by a collaborator can not be opened by non-collaborator..something like that). Unless that the fix is actually solving the problem but something is wrong on my end?

**Comment by oesteban** [comment] 2017-02-03 07:10
Could you send me the csv file and the output from mriqc?

Thanks!

**Comment by parekhpravesh** [comment] 2017-02-03 07:16
Hello,
Seems like I can't upload a .csv file (strange) so I have saved it as a .xls file and attached the same.
I had redirected the terminal output of the run to a text file (the same is attached). This however does not contain the warnings and the error message from above (which were displayed on the terminal).

[run1_server_log.txt](https://github.com/poldracklab/mriqc/files/749761/run1_server_log.txt)


[anatMRIQC.xlsx](https://github.com/poldracklab/mriqc/files/749762/anatMRIQC.xlsx)

Thanks!

**Comment by oesteban** [comment] 2017-02-03 07:19
I'll take a look early tomorrow. Thanks very much

**Comment by parekhpravesh** [comment] 2017-02-03 07:39
P.S: I just noticed that in the .csv the subject_id column seems to have removed the zero padding. The attachment is using the ds001 dataset where subjects are named sub-01, sub-02, and so on. However the subject_id filed simply reads as 1, 2, 3...instead of 01, 02, and 03.
In an alternate run, where subjects were named sub-HS032, sub-HS034, etc. the subject_id reads HS032 and HS034 as expected.

**Comment by oesteban** [comment] 2017-02-03 16:46
Hi @parekhpravesh, I don't find your error in the log file you submitted. Apparently, everything worked out ok in that run.

Regarding the zero padding trimmed in the xlsx file you sent: is it also happening in the output csv file?

**Comment by parekhpravesh** [comment] 2017-02-03 16:57
Hello @oesteban ,
The error messages were displayed on the terminal (and hence the log files are clean). This happens on every run...the warning messages and the error messages on the terminal once the .csv is generated. Regarding the zero padding, I would only be able to confirm that in the morning now (I have left lab for the day)...sorry about that.

**Comment by parekhpravesh** [comment] 2017-02-04 12:15
Greetings!
Sorry about the delay in updating...
1) The subject tags are fine. I was opening the sheets in Excel and so couldn't see the leading zero (Libre Office and Notepad++ confirm that the subject id is correct).

2) The error about list index out of range persists. It turns up even when "--verbose-reports" is not passed. If you would like me to update my installation and recheck, do let me know.


Thanks!

**Comment by oesteban** [comment] 2017-02-04 18:26
Hi @parekhpravesh 

Could you please:
```
pip install git+https://github.com/oesteban/mriqc.git@fix/351
```
Confirm that mriqc is using version 0.9.0-rc3:
```
mriqc -h
```

And then check if the error is still happening?

Thank you

**Comment by parekhpravesh** [comment] 2017-02-04 18:28
@oesteban Sure...will do so and update asap (probably by tomorrow morning; we have just scheduled a few server updates)

**Comment by oesteban** [comment] 2017-02-05 18:27
Finally reproduced this myself. A fix will be coming soon.

**Comment by oesteban** [comment] 2017-02-06 17:29
Got it. This is what is happening: mriqc does not deal correctly the absence of functional derivatives (a json file per input image with the calculated quality metrics).

I guess you are running mriqc only on T1w data. So everything works well (actually your csv table for the anatomical images is created, and you should also have an ```out/reports/anat_group.html``` file generated), but it breaks trying to generate those (csv table and group html file) for the functional images which do not exist.

I am fixing the group analysis level to fail with an informative warning (#372).

**Closed** 2017-02-06 19:21 UTC
Labels: bug

**Comment by parekhpravesh** [comment] 2017-02-07 13:26
Hello @oesteban! 
Apologies, I was away. I seem to have missed all the fun while the commits and updates were happening.
Indeed, I was running the tests only on the anatomical scans and that the .csv and anat-group.html are both getting created.

Thanks a lot!
