### ISSUE TITLE
MRIQC should handle data with AFNI extensions in the header

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/mriqc#686] opened 2018-02-09 18:11 UTC
I'm attaching MRIQC logs that include errors caused by AFNI extensions in the headers of some of the nifti files. Clearing the extensions of the nifti files solves these issues.
[MRIQC_out .txt](https://github.com/poldracklab/mriqc/files/1711993/MRIQC_out.txt)

Here is some code from FMRIPREP that solves a similar issue:
https://github.com/poldracklab/niworkflows/pull/188/files#diff-f8673c789e80bea243d3ca9b83e3de2cR298

Here's an example from the attached file:

2018-01-29 02:14:19,645 interface:INFO stderr 2018-01-29T02:14:19.644922:++ Max displacement in automask = 0.12 (mm) at sub-brick 18
2018-01-29 02:14:19,645 interface:INFO stderr 2018-01-29T02:14:19.644922:++ Max delta displ  in automask = 0.13 (mm) at sub-brick 19
2018-01-29 02:14:20,147 interface:INFO stderr 2018-01-29T02:14:20.147094:** ERROR: nifti_image_write_hdr_img: NBL does not match nim
2018-01-29 02:14:20,150 interface:INFO stderr 2018-01-29T02:14:20.150087:++ Max displacement in automask = 0.38 (mm) at sub-brick 18
2018-01-29 02:14:20,150 interface:INFO stderr 2018-01-29T02:14:20.150087:++ Max delta displ  in automask = 0.12 (mm) at sub-brick 3
2018-01-29 02:14:20,151 interface:INFO stderr 2018-01-29T02:14:20.150087:** ERROR: nifti_image_write_hdr_img: NBL does not match nim
2018-01-29 02:14:20,156 interface:INFO stderr 2018-01-29T02:14:20.156274:++ Max displacement in automask = 0.24 (mm) at sub-brick 15
2018-01-29 02:14:20,156 interface:INFO stderr 2018-01-29T02:14:20.156274:++ Max delta displ  in automask = 0.15 (mm) at sub-brick 2
2018-01-29 02:14:20,157 interface:INFO stderr 2018-01-29T02:14:20.156274:** ERROR: nifti_image_write_hdr_img: NBL does not match nim
2018-01-29 02:14:20,667 interface:INFO stderr 2018-01-29T02:14:20.666991:++ Max displacement in automask = 0.14 (mm) at sub-brick 14
2018-01-29 02:14:20,667 interface:INFO stderr 2018-01-29T02:14:20.666991:++ Max delta displ  in automask = 0.13 (mm) at sub-brick 14
2018-01-29 02:14:20,668 interface:INFO stderr 2018-01-29T02:14:20.666991:** ERROR: nifti_image_write_hdr_img: NBL does not match nim

**Comment by effigies** [comment] 2018-02-09 18:45
This issue actually seems to arise from that same interface (`EstimateReferenceImage`) that's fixed in niworkflows...

What version of MRIQC were you using, and what was the full command invoked? Did you have anything in your `PYTHONPATH`?

**Comment by jbwexler** [comment] 2018-02-09 22:08
1) The version was MRIQC 9.6 (see below).

2) The commands looked like this (with differing participant labels of course):
/work/02710/chrifilo/singularity_containers/poldracklab_mriqc_0.9.6-2017-06-03-ba2908056b70.img /work/03201/jbwexler/stampede2/ds000257_R1.0.0 /work/03201/jbwexler/stampede2/ds000257_R1.0.0/derivatives/mriqc/ participant --participant_label 01

3) I don't know of a way to retrieve the PYTHONPATH but when I echo it now it looks like this:
/opt/apps/intel17/impi17_0/python/2.7.13/lib/python2.7/site-packages

**Comment by effigies** [comment] 2018-02-10 13:03
If the date on that is right (2017-06-03), then the issue is probably that the version of MRIQC is too old.

**Comment by jbwexler** [comment] 2018-02-12 18:50
That's the latest we have on tacc as a singularity container. But I'll upload to openneuro and see if it runs there. I assume that version is newer?

**Comment by chrisfilo** [comment] 2018-02-12 18:56
Yup!

Best,
Chris

**Comment by effigies** [comment] 2019-03-05 13:00
From the conversation, it looks like this should probably be closed.

**Closed** 2020-03-24 17:28 UTC
Labels: bug, fMRI, sMRI
