### ISSUE TITLE
failed to run on host ymu040-110.ym.edu.tw

### ISSUE THREAD

**Issue by noelkuo** [poldracklab/mriqc#423] opened 2017-03-14 02:57 UTC
Dear all:
I followed the installation in mriqc web and tested the BIDS data or our dataset. However, we had some error in processing data and can't finish the reports.

For example:
workflow ERROR:
u'Node ArtifactMask.a4 failed to run on host ymu040-110.ym.edu.tw
workflow ERROR:
u'Node SpatialNormalization.a4 failed to run on host ymu040-110.ym.edu.tw
workflow ERROR:
u'Node measures.a4 failed to run on host ymu040-110.ym.edu.tw

Some data will miss the process of ArtifactMask or SpatialNormalization.
Do you have any suggestion for this error? Thanks

**Comment by chrisfilo** [comment] 2017-03-14 03:01
Cold you share the full terminal output and the exact command line you used?

**Comment by noelkuo** [comment] 2017-03-14 03:25
Our command : mriqc ~/Desktop/Data/ds001_Group_TEST2/ ~/Desktop/Data/ds001_Group_TEST2/out/ participant -d anat -w ~/Desktop/Data/ds001_Group_TEST2/work

![screenshot-2](https://cloud.githubusercontent.com/assets/20572721/23884554/4ad44a52-08a8-11e7-892e-c8eb3ea2ac65.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/20572721/23884610/b739da5e-08a8-11e7-92dc-0521648babc6.png)

**Comment by chrisfilo** [comment] 2017-03-14 03:51
This is a duplicate of https://github.com/poldracklab/mriqc/issues/379 - your input data is corrupted. What software did you use to create those nifti files?

**Comment by noelkuo** [comment] 2017-03-14 04:07
The ds001_Group_TEST2 is from BIDS dataset. We didn't process these data, and directly use mriqc to measure the QC index.
In our data, we used the dcm2nii (mricron) to creat the nifti files

**Comment by chrisfilo** [comment] 2017-03-14 04:10
Where did you download/obtained ds001_Group_TEST2 from?

**Comment by noelkuo** [comment] 2017-03-14 04:24
We download the BIDS data (ds001.tar) from https://drive.google.com/drive/folders/0B2JWN60ZLkgkMGlUY3B4MXZIZW8

We selected the 5 subjects to test the MRIQC in our system, and we change the filename (ds001_Group_TEST2).

<img width="848" alt="screenshot-5" src="https://cloud.githubusercontent.com/assets/20572721/23885828/01fb52ea-08b1-11e7-8f31-60f5ff0f0724.png">

**Comment by chrisfilo** [comment] 2017-03-14 04:48
I just downloaded this dataset from the same source and verified the integrity of all nifti files in it. I also tried the updated version of ds001 available at https://openfmri.org/dataset/ds000001/ In both cases all files were not corrupted.

However, if the input data were corrupted it would've been the `conform`  Node that would fail. Could you redownload the dataset, remove the `work` directory and try running MRIQC again?

**Comment by noelkuo** [comment] 2017-03-14 04:54
Thanks, I'll try it again

**Comment by noelkuo** [comment] 2017-03-16 02:13
Hi, Chrisfilo:
We tried to redownload the dataset, and our command line: 
mriqc ds001_Group ds001_Group/out participant -d anat. 
However, we still had the same error and some data can't finish it 
Error message:
	 ***********************************
170316-07:57:52,561 workflow ERROR:
	 could not run node: workflow_enumerator.anatMRIQC.SpatialNormalization.a6
170316-07:57:52,561 workflow INFO:
	 crashfile: /root/Desktop/Data/ds001_Group/out/logs/crash-20170315-203431-root-SpatialNormalization.a6-4263713b-c3fb-49b1-bc96-0d1eaac00994.pklz
170316-07:57:52,561 workflow ERROR:
	 could not run node: workflow_enumerator.anatMRIQC.AFNISkullStripWorkflow.skullstrip.a0
170316-07:57:52,561 workflow INFO:
	 crashfile: /root/Desktop/Data/ds001_Group/out/logs/crash-20170315-222832-root-skullstrip.a0-23d66f6f-31ff-4e96-bbd1-863a6d479306.pklz
170316-07:57:52,561 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/usr/local/bin/mriqc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mriqc/bin/mriqc_run.py", line 253, in main
    workflow.run(**plugin_settings)
  File "/usr/local/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 583, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/usr/local/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

<img width="438" alt="2017-03-15 7 11 39" src="https://cloud.githubusercontent.com/assets/20572721/23978809/e7dc5ad6-0a30-11e7-9f18-4414783182cf.png">
![screenshot-1](https://cloud.githubusercontent.com/assets/20572721/23978811/ec754f12-0a30-11e7-9a67-ebed03e59a7e.png)

**Comment by chrisfilo** [comment] 2017-03-16 02:29
This looks like a different error - could post the full console output?

**Comment by noelkuo** [comment] 2017-03-16 02:33
This's the full output and some data can't finish it. 
![screenshot-2](https://cloud.githubusercontent.com/assets/20572721/23979332/e7d95cf2-0a33-11e7-82e3-46d83fb493de.png)

**Comment by chrisfilo** [comment] 2017-03-16 02:36
I mean the text printed on the console. All of it. Not just the end.

**Comment by chrisfilo** [comment] 2017-03-16 03:00
BTW it seems that you only had problems with sub-01? Other subjects run smoothly?

**Comment by noelkuo** [comment] 2017-03-16 03:49
We will try it again and save the console message.
Actually, we tested the 5 subjects (sub-01, sub-02, sub-03, sub-04, and sub-05), the MRIQC finished successfully. However, we tested the 10 subjects, we had the problems with sub-01, sub-07 and we found the error is random.
Because we tested it three days ago, the failed results were sub-04,sub-07, and sub-09.
So we don't understand why we test the 10 subjects will be failed.

**Comment by noelkuo** [comment] 2017-03-16 05:35
Hi, Chrisfilo:
Here is the log text on the console
[Output.txt](https://github.com/poldracklab/mriqc/files/846760/Output.txt)

**Comment by chrisfilo** [comment] 2017-03-16 05:46
Indeed this is the CRC error again - but this time happening at different Node. I cannot replicate this on any of our machines. I am wondering if this is related to some hardware problem on your system - corrupted harddrive or RAM. This would explain the randomness of the issue. Have you tried running mriqc on another machine?

**Comment by noelkuo** [comment] 2017-03-16 05:52
No, we didn't try running mriqc on another machine. Maybe our testing computer isn't powerful.
I will try it on another machine.
Thanks for your suggestion.

**Comment by oesteban** [comment] 2017-04-05 01:33
Hi @noelkuo, did you finally fix this issue?

**Comment by noelkuo** [comment] 2017-04-05 02:22
Hi @oesteban :
Because our other workstations are still running other projects, I can't try mriqc on another machine temporarily. If we have the news, we will tell you. Thanks

**Comment by oesteban** [comment] 2017-05-23 22:02
Hi @noelkuo, any news on this?

**Comment by oesteban** [comment] 2017-05-25 22:42
Feel free to reopen if needed, I'm cleaning up open issues.

**Closed by oesteban** 2017-05-25 22:42 UTC
