### ISSUE TITLE
Make sure that mriqc can analyze multiband data on ls5

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#35] opened 2016-02-16 07:04 UTC
Memory requirements of multiband data combined with specific submit restriction of ls5 can be problematic and require new execution modes.

**Comment by oesteban** [comment] 2016-02-16 16:11
I will assign this to @wtriplett if he is happy with it :)

**Comment by wtriplett** [comment] 2016-02-16 16:16
I'm happy with it! :)

**Comment by wtriplett** [comment] 2016-02-20 22:17
So right off the bat the anatomical workflow is too much for a lonestar5 node when it starts `fast`, unless the number of threads are restricted in multiproc. Seems like 15 threads is about the max it can take with each `fast` at just under 4 GB, but even that's making me a little nervous. Cheaper than iTunes, though!

**Comment by wtriplett** [comment] 2016-03-21 01:13
The functional workflow only was run on a single LS5 node with 24 CPUs (48 hyperthreaded). No --nthreads option was specified, allowing MultiProc to use all available CPU including the hyperthreaded ones. 

Start time: 160319-22:55:47
End time: 160320-03:07:43

Memory usage was moderate to high during the times I checked. The workflow failed during the execution of the `measures` node with the below two crash files. I re-ran the workflow and watched the CPU usage during various stages of execution, and noticed that the mriqc processes was consuming between 1.4 and 4.4 GB each, possibly all trying to run `measures` at the same time. The crash files from the unsupervised mriqc run are below. Let me know if I can provide additional info -- I still have the work folder on TACC in my $SCRATCH.

```
File: crash-20160320-030612-wtriplet-measures.a116.pklz
Node: fMRIQC.measures.a116
Working directory: /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-083.task-rest_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-083..func..sub-01_ses-083_task-rest_run-001_bold.nii.gz/measures


Node inputs:

direction = all
ignore_exception = False
in_epi = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-083.task-rest_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-083..func..sub-01_ses-083_task-rest_run-001_bold.nii.gz/mean/sub-01_ses-083_task-rest_run-001_bold_calc_resample_volreg_tstat.nii.gz
in_hmc = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/fMRI_HMC/_data_sub-01.ses-083.task-rest_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-083..func..sub-01_ses-083_task-rest_run-001_bold.nii.gz/motion_correct_A/sub-01_ses-083_task-rest_run-001_bold_calc_resample_volreg.nii.gz
in_mask = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/fMRIBrainMask/_data_sub-01.ses-083.task-rest_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-083..func..sub-01_ses-083_task-rest_run-001_bold.nii.gz/afni_msk/sub-01_ses-083_task-rest_run-001_bold_calc_resample_volreg_mask.nii.gz
in_tsnr = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-083.task-rest_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-083..func..sub-01_ses-083_task-rest_run-001_bold.nii.gz/compute_tsnr/tsnr.nii.gz



Traceback: 
Traceback (most recent call last):
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 989, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/interfaces/qc.py", line 226, in _run_interface
    self._results['dvars'] = dvars(hmcdata, mskdata).mean(axis=0)[0]
  File "/home1/03872/wtriplet/software/mriqc/mriqc/qc/functional.py", line 159, in dvars
    dvars_nstd = func_diff.std(axis=0)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 124, in _std
    keepdims=keepdims)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 101, in _var
    x = asanyarray(arr - arrmean)
MemoryError: 
Interface FunctionalQC failed to run.
```
and

```
File: crash-20160320-030613-wtriplet-measures.a135.pklz
Node: fMRIQC.measures.a135
Working directory: /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-095.task-objects_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-095..func..sub-01_ses-095_task-objects_run-001_bold.nii.gz/measures


Node inputs:

direction = all
ignore_exception = False
in_epi = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-095.task-objects_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-095..func..sub-01_ses-095_task-objects_run-001_bold.nii.gz/mean/sub-01_ses-095_task-objects_run-001_bold_calc_resample_volreg_tstat.nii.gz
in_hmc = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/fMRI_HMC/_data_sub-01.ses-095.task-objects_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-095..func..sub-01_ses-095_task-objects_run-001_bold.nii.gz/motion_correct_A/sub-01_ses-095_task-objects_run-001_bold_calc_resample_volreg.nii.gz
in_mask = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/fMRIBrainMask/_data_sub-01.ses-095.task-objects_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-095..func..sub-01_ses-095_task-objects_run-001_bold.nii.gz/afni_msk/sub-01_ses-095_task-objects_run-001_bold_calc_resample_volreg_mask.nii.gz
in_tsnr = /scratch/03872/wtriplet/ds031.qcpwrk/fMRIQC/_data_sub-01.ses-095.task-objects_run-001...home1..03872..wtriplet..openfmri..HISTORICAL_DATA_TO_BIDS..999_AllUncompressed..ds000031..ds031..sub-01..ses-095..func..sub-01_ses-095_task-objects_run-001_bold.nii.gz/compute_tsnr/tsnr.nii.gz



Traceback: 
Traceback (most recent call last):
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/plugins/multiproc.py", line 19, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 392, in run
    self._run_interface()
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 502, in _run_interface
    self._result = self._run_command(execute)
  File "/home1/03872/wtriplet/software/nipype/nipype/pipeline/engine/nodes.py", line 628, in _run_command
    result = self._interface.run()
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 1032, in run
    runtime = self._run_wrapper(runtime)
  File "/home1/03872/wtriplet/software/nipype/nipype/interfaces/base.py", line 989, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home1/03872/wtriplet/software/mriqc/mriqc/interfaces/qc.py", line 193, in _run_interface
    hmcdata = np.nan_to_num(hmcnii.get_data())
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/nibabel/spatialimages.py", line 582, in get_data
    data = np.asanyarray(self._dataobj)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 525, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 144, in __array__
    raw_data = self.get_unscaled()
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/nibabel/arrayproxy.py", line 139, in get_unscaled
    mmap=self._mmap)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/site-packages/nibabel/volumeutils.py", line 517, in array_from_file
    n_read = infile.readinto(data_bytes)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/gzip.py", line 320, in _read
    self._add_read_data( uncompress )
  File "/work/03872/wtriplet/lonestar/anaconda/lib/python2.7/gzip.py", line 338, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError: 
Interface FunctionalQC failed to run.
```

**Comment by oesteban** [comment] 2016-03-21 15:48
Thanks a lot @wtriplett, this is really good material to work on.

**Comment by oesteban** [comment] 2016-03-25 16:57
Hi @chrisfilo, after looking deep into this I realized where the problem is. When I included checking matrix size, pixel spacing, tr and number of time points, I implemented it using nibabel.

This is the typical MemoryError when you try to open very large, gzipped, nifti files with nibabel. I can't tell if this particular errror that @wtriplett found is because the files are too large themselves or because of the fact that it would be trying to open 48 files at the same time.

**Comment by chrisfilo** [comment] 2016-03-25 17:02
We should do some memory profiling on a Linear run to figure this out.

BTW it's not just checking matrix size and pixel dimensions which caused
this particular MemoryError. It was reading the data itself:
https://github.com/poldracklab/mriqc/blob/f951560886c63305cfa5d782c1f81288fd85857d/mriqc/interfaces/qc.py#L193

**Comment by oesteban** [comment] 2016-03-25 17:10
True, I did not observe this. Then this is a big issue :(

**Comment by wtriplett** [comment] 2016-03-27 18:28
Memory profiling on Linear:
(see: https://github.com/wtriplett/mem_ps_sampler_example)

Run on one ls5 node against a simple single subject data set with 1 anatomical (0.8 mm3 resolution) and 1 functional (multi band):
```
sub-023/anat/sub-023_T1w.nii.gz int16 [256, 256, 256] 0.80x0.80x0.80   sform 
sub-023/func/sub-023_task-training_run-03_bold.nii.gz float32 [ 96,  96,  64, 329] 2.40x2.40x2.40x1.16   sform
```

Sampling the output of `ps uawww` every second during execution provides this report:

![rplot](https://cloud.githubusercontent.com/assets/1926804/14066882/4388f35e-f40b-11e5-8dd7-3a11f98a154e.png)

Maybe this is a start, and then we can see what could be added or improved about the sampling. I think trying to join this with the log from the mriqc stdout would be a good next step, but maybe it clear what's going on without needing to do that.

**Comment by chrisfilo** [comment] 2016-03-27 19:01
This is very useful! 3dresample and 3dcalc are things that probably coulb
be easily optimised.

On Sun, Mar 27, 2016 at 11:28 AM, William Triplett <notifications@github.com

**Comment by wtriplett** [comment] 2016-03-28 17:16
The overall memory footprint doesn't seem unreasonable really. Trying to run 48 instances of this in parallel on a single LS5 node w/ 65GB physical ram and no swap might be asking a bit much though.

It would be great to find a way to spread the work out across multiple nodes on ls5, but it seems that LS5's configuration of providing whole-nodes per job and its max jobs per queue limit rule out slurmgraph (although slurmgraph plugin does work well otherwise on LS5!)

Having an estimate of the worst case memory usage per subject can help me better set --nthreads and give a balance between parallelization and successful workflow execution (hopefully!). Also submitting --skip-functional to one node and --skip-anatomical to another also can cut the time roughly in half.

**Comment by vsoch** [comment] 2016-03-28 17:22
Sherlock, +1

**Comment by wtriplett** [comment] 2016-03-30 14:49
Hi, for completness I attach a profile of multiproc threads = 48 run on the full dataset with --skip-anatomical. (60 subjects, 8 fMRI runs each).

The dark plot symbols are the program's memory usage. The colored lines are system memory partitions. The vertical dotted lines indicate crashed programs (using the timestamp from crash pickles). Its cool how the system starts digging into the cached mem when things get tight.

![rplot](https://cloud.githubusercontent.com/assets/1926804/14146099/53672754-f64b-11e5-9141-8188fd2feea1.png)

**Comment by chrisfilo** [comment] 2016-03-30 16:19
Out of curiosity - what did you use for profiling?

**Comment by wtriplett** [comment] 2016-03-30 16:25
A combination of `cat /proc/meminfo` and `ps -jFl -u wtriplet -U wtriplet` sampled continuously in the background during execution. The code and such is here, although i'm afraid its not too well organized at the moment: https://github.com/wtriplett/mem_ps_sampler_example

**Comment by oesteban** [comment] 2016-04-13 22:40
What do you think if I close this issue, and get a docker version ready for @wtriplett to test? We probably want to move to a subject&session paradigm and then merge all them together with EoD (End-of-Day), as we were speaking the other day. Is that correct, @chrisfilo ?

**Comment by chrisfilo** [comment] 2016-04-13 22:42
sounds good to me (although docker will not work on ls5, but I get your
point)

**Comment by oesteban** [comment] 2016-04-13 22:44
Yes, the idea is to get direct access to the docker runners in TACC and start the benchmarking there.

**Closed by oesteban** 2016-04-13 22:44 UTC
Labels: testing

**Comment by chrisfilo** [comment] 2016-04-13 22:47
I would not count on gaining access to docker runner, but this issue is
independent of sending one job per subject (which can be done with and
without docker).

**Comment by oesteban** [comment] 2016-04-13 22:55
Well, it is connected to sending one job per subject, right? The bottleneck is when it tries to open several fmri datasets at the same time in one multiproc job, isn't it?

**Comment by chrisfilo** [comment] 2016-04-13 23:08
When I said "this issue" I was referring to not being able to access Docker
runners directly. All is good.
