### ISSUE TITLE
Time out for no apparent reason

### ISSUE THREAD

**Issue by jokedurnez** [poldracklab/mriqc#380] opened 2017-02-07 18:22 UTC
Some jobs (3.75% of the total sample) showed a time out for no apparent reason (no error apart from [#378](https://github.com/poldracklab/mriqc/issues/378)).  The logs are here:
[00_MRIQC.txt](https://github.com/poldracklab/mriqc/files/758594/00_MRIQC.txt) and [01_mriqc.txt](https://github.com/poldracklab/mriqc/files/758595/01_mriqc.txt)

**Comment by chrisfilo** [comment] 2017-02-07 18:27
1. How long did the job run for before timing out?
2. How long on average a successful job runs for (using similar data)?
3. Is it reproducible? Did you try rerunning those jobs?

**Comment by jokedurnez** [comment] 2017-02-07 18:52
1. The job ran for 6 hours
2. The average succesful job runs for 3-4 hours
3. Will try now.

**Comment by jokedurnez** [comment] 2017-02-07 19:07
(should I remove anything before restarting it or can I just try to continue the job?)

**Comment by chrisfilo** [comment] 2017-02-07 19:10
I would submit two jobs: one with a fresh working directory (empty) and one
with the old one. Also, try upping the timeout to 12h.

**Comment by oesteban** [comment] 2017-05-25 22:35
Possibly related: https://github.com/poldracklab/fmriprep/issues/534

**Comment by oesteban** [comment] 2017-05-25 22:40
Looking into the logs, it seems that job actually finished the full workflow. The job started around 05:26:22 and finished 08:18:08 (around 3h). So, if the wallclock time was 6h it means mriqc didn't exit when done for 3h.

I'll check on this with 0.9.5.

**Comment by oesteban** [comment] 2018-05-04 03:03
Possibly related: nipy/nipype#2548

**Comment by oesteban** [comment] 2018-08-09 23:33
This is very likely to be related to that problem of Python's `multiprocessing`. Seems to be fixed now.

**Closed by oesteban** 2018-08-09 23:33 UTC
Labels: bug
