### ISSUE TITLE
mriqc UploadMetrics errors

### ISSUE THREAD

**Issue by oricon** [poldracklab/mriqc#750] opened 2018-09-05 15:15 UTC
I'm running mriqc for the first time using singularity and running into some errors with UploadMetrics nodes. I'm getting multiple errors for different UploadMetrics nodes, but they all give a similar error. I'm going to try the --no-sub flag to see if this solves the error, but wanted to see if this is a bug, or if I need to change another setting. I have singularity 2.5.2 and I'm running the latest mriqc.

> 180905-02:23:49,759 nipype.workflow ERROR:
> 	 Node UploadMetrics.a3 failed to run on host c0134.brazos.tamu.edu.
> 2018-09-05 02:23:49,759 nipype.workflow:ERROR Node UploadMetrics.a3 failed to run on host c0134.brazos.tamu.edu.
> 180905-02:23:49,759 nipype.workflow ERROR:
> 	 Saving crash info to /fdata/scratch/joseph.orr/mriqc/lcmn/CBLM2/logs/crash-20180905-022349-joseph.orr-UploadMetrics.a3-d7bc9623-2391-4fde-bf0d-429f696225c0.txt
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
>     result['result'] = node.run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
>     runtime = self._run_interface(runtime)
>   File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/webapi.py", line 152, in _run_interface
>     self._results['api_id'] = response.json()['_id']
> AttributeError: 'Bunch' object has no attribute 'json'

The crash file is attached.
[workflow_enumerator.funcMRIQC.UploadMetrics_crash.txt](https://github.com/poldracklab/mriqc/files/2353363/workflow_enumerator.funcMRIQC.UploadMetrics_crash.txt)

**Comment by Shotgunosine** [comment] 2019-02-05 19:42
I got the same error with a clean working directory and hacked the mriqc_run.py to output pklz instead of txt. It looks like the problem is that the response object is a Nipype Bunch. When I look at the contents of response here's what I get:
```
[('status_code', 1), ('text', "QC metrics failed to upload due to connection error shown below:\nHTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Max retries exceeded with url: /api/v1/T1w (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b215c72a6d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))")]
```

So it basically looks like we could improve the handling of the errors on that request to produce a less ambiguous error message.

**Comment by benjamin-zimmerman** [comment] 2019-02-21 22:54
This hasn't been addressed yet has it? I can run without an error, but need to use the --no-sub flag.

**Comment by oesteban** [comment] 2019-02-21 23:12
Hi @rwblair, do you know if this should be working now?

**Comment by oesteban** [comment] 2019-04-05 16:15
Fixed in https://github.com/poldracklab/mriqc/commit/a2393c2f76bb2ad7a92af766f188f11fdd1a0842

**Closed by oesteban** 2019-04-05 16:15 UTC
Labels: bug
