### ISSUE TITLE
RotationMask fails on T2w images

### ISSUE THREAD

**Issue by stjep** [poldracklab/mriqc#620] opened 2017-08-17 20:32 UTC
After playing around a bit with mriqc on individual bold runs, I wanted to set it up for a new data set. This data set includes T1w, T2w, spiral BOLD and DTI data. I get the following crash log for two subjects' T2w images (mriqc is still running, so there may be more to come). Any suggestions on what to investigate to figure out what might be causing this?

```
Node: workflow_enumerator.anatMRIQCT2w.AirMaskWorkflow.RotationMask
Working directory: /work/workflow_enumerator/anatMRIQCT2w/AirMaskWorkflow/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/RotationMask

Node inputs:

ignore_exception = False
in_file = /work/workflow_enumerator/anatMRIQCT2w/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/conform/sub-07_ses-day1_T2w_conformed.nii.gz

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/anatomical.py", line 367, in _run_interface
    mask = nd.binary_opening(mask, structure=struc).astype(
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 606, in binary_opening
    origin)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 378, in binary_erosion
    output, border_value, origin, 0, brute_force)
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 228, in _binary_erosion
    raise RuntimeError('structure and input must have same dimensionality')
RuntimeError: structure and input must have same dimensionality
Interface RotationMask failed to run. 
```

**Comment by stjep** [comment] 2017-08-17 20:33
Additionally, those same files also throw up the following separate error:

```
Node: workflow_enumerator.anatMRIQCT2w.ReportsWorkflow.PlotMosaicNoise
Working directory: /work/workflow_enumerator/anatMRIQCT2w/ReportsWorkflow/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/PlotMosaicNoise

Node inputs:

annotate = True
bbox_mask_file = <undefined>
cmap = viridis_r
dpi = 300
figsize = (11.69, 8.27)
ignore_exception = False
in_file = /work/workflow_enumerator/anatMRIQCT2w/_in_file_..data..sub-07..ses-day1..anat..sub-07_ses-day1_T2w.nii.gz/conform/sub-07_ses-day1_T2w_conformed.nii.gz
only_noise = True
out_file = plot_anat_mosaic2_noise.svg
title = noise enhanced

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 372, in run
    self._run_interface()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 482, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 613, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1083, in run
    runtime = self._run_wrapper(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1031, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/viz.py", line 120, in _run_interface
    annotate=self.inputs.annotate)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/viz/utils.py", line 261, in plot_mosaic
    label='%d' % z_val, annotate=annotate)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/viz/utils.py", line 49, in plot_slice
    phys_sp = np.array(spacing) * dslice.shape
ValueError: operands could not be broadcast together with shapes (2,) (3,) 
Interface PlotMosaic failed to run. 
```

**Comment by oesteban** [comment] 2017-08-25 16:20
Hi @stjep, could you privately share that sub-07+ses-day1 subject from your dataset with us, so that we can replicate the problem?

**Comment by stjep** [comment] 2017-08-25 18:16
@oesteban, sure where would you like me to send the nifti?

**Comment by oesteban** [comment] 2017-08-25 18:19
Yes, a nifti would be enough. If you also have some metadata (sidecar JSON) I would also appreciate that part, but it is not mandatory.

Thanks!

**Comment by stjep** [comment] 2017-08-25 18:40
I should clarify that this error seems to only relate to the T2w images for this data set. The func and T1w images go through mriqc fine without any problems. I'll send through one of the T2w shortly (look for it in your email), and the relevant metadata.

**Comment by oesteban** [comment] 2017-08-25 18:43
Yes, when I asked for the whole subject I had FMRIPREP in mind for some
reason.

The T2w & metadata should do.

Thanks!

On Aug 25, 2017 11:40, "Dan Stjepanović" <notifications@github.com> wrote:

I should clarify that this error seems to only relate to the T2w images for
this data set. The func and T1w images go through mriqc fine without any
problems. I'll send through one of the T2w shortly (look for it in your
email), and the relevant metadata.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/mriqc/issues/620#issuecomment-325005015>,
or mute the thread

**Comment by oesteban** [comment] 2018-08-15 22:06
Coming back to this issue, now I notice this is a duplicate of #660. A patch for it has been added (#738), although it seems that your T2w images are 4D (probably they only are size 1 in the last dimension). You may want to fix that (e.g. using [`nibabel.funcs.squeeze_image`](http://nipy.org/nibabel/reference/nibabel.funcs.html#nibabel.funcs.squeeze_image)).

Anyways, I'll release soon a new version including this change that will allow you to run your T2w images.

**Closed by oesteban** 2018-08-15 22:06 UTC
Labels: bug, sMRI
